import xml.etree.ElementTree as ET
CONST_MAXSIZE = None
CONST_MINSIZE = None
CONST_STOP_SPEED = None
CONST_SEARCH_DISTANCE = None
CONST_MIN_PLATOON_DISTANCE = None
CONST_EXIT_PLATOON_BUFFER = None
CONST_SPLIT_DISTANCE = None
CONST_LANE_CHANGE_DURATION = None
CONST_PROPORTION_CONNECTED_VEHICLES = None
CONST_TAU_UNCONNECTED = None
CONST_TAU_CONNECTED_NO_PLATOON = None
CONST_TAU_CONNECTED_PLATOON = None
CONST_ENABLE_PLATOONING = None
CONST_CURR_MAP = None
CONST_MEASURE_ALL_JUNCTIONS = None
CONST_MEASUREMENT_INTERVAL = None
CONST_FLOW_FILE_NAME = None
CONST_FLOW_SIMULATION_TIME = None
CONST_FLOW_CUT_OFF = None
CONST_JUNCTIONS_TO_MEASURE = None
CONST_EXPERIMENT_NAME = None
#CONST_GUI = None

def UpdateParameters(SettingsName):
	tree = ET.parse(SettingsName)
	root = tree.getroot()
	global CONST_MAXSIZE, CONST_MINSIZE, CONST_STOP_SPEED, CONST_SEARCH_DISTANCE, CONST_MIN_PLATOON_DISTANCE, CONST_EXIT_PLATOON_BUFFER, CONST_SPLIT_DISTANCE, CONST_LANE_CHANGE_DURATION, CONST_PROPORTION_CONNECTED_VEHICLES, CONST_TAU_UNCONNECTED,CONST_TAU_CONNECTED_NO_PLATOON
	global CONST_TAU_CONNECTED_PLATOON, CONST_ENABLE_PLATOONING, CONST_CURR_MAP, CONST_MEASURE_ALL_JUNCTIONS, CONST_MEASUREMENT_INTERVAL, CONST_FLOW_FILE_NAME, CONST_FLOW_SIMULATION_TIME, CONST_FLOW_CUT_OFF, CONST_JUNCTIONS_TO_MEASURE, CONST_EXPERIMENT_NAME, CONST_GUI
	CONST_MAXSIZE = int(root.find('CONST_MAXSIZE').text)
	CONST_MINSIZE = int(root.find('CONST_MINSIZE').text)
	CONST_STOP_SPEED = int(root.find('CONST_STOP_SPEED').text)
	CONST_SEARCH_DISTANCE = int(root.find('CONST_SEARCH_DISTANCE').text)
	CONST_MIN_PLATOON_DISTANCE = int(root.find('CONST_MIN_PLATOON_DISTANCE').text)
	CONST_EXIT_PLATOON_BUFFER = int(root.find('CONST_EXIT_PLATOON_BUFFER').text)
	CONST_SPLIT_DISTANCE = int(root.find('CONST_SPLIT_DISTANCE').text)
	CONST_LANE_CHANGE_DURATION = int(root.find('CONST_LANE_CHANGE_DURATION').text)
	CONST_PROPORTION_CONNECTED_VEHICLES = float(root.find('CONST_PROPORTION_CONNECTED_VEHICLES').text)
	CONST_TAU_UNCONNECTED = float(root.find('CONST_TAU_UNCONNECTED').text)
	CONST_TAU_CONNECTED_NO_PLATOON = float(root.find('CONST_TAU_CONNECTED_NO_PLATOON').text)
	CONST_TAU_CONNECTED_PLATOON = float(root.find('CONST_TAU_CONNECTED_PLATOON').text)
	CONST_ENABLE_PLATOONING = True if (root.find('CONST_ENABLE_PLATOONING').text.lower() == 'true') else False
	CONST_CURR_MAP = root.find('CONST_CURR_MAP').text
	CONST_MEASURE_ALL_JUNCTIONS = True if (root.find('CONST_MEASURE_ALL_JUNCTIONS').text.lower() == 'true') else False
	CONST_MEASUREMENT_INTERVAL = int(root.find('CONST_MEASUREMENT_INTERVAL').text)
	CONST_FLOW_FILE_NAME = root.find('CONST_FLOW_FILE_NAME').text
	CONST_FLOW_SIMULATION_TIME = int(root.find('CONST_FLOW_SIMULATION_TIME').text)
	CONST_FLOW_CUT_OFF = True if (root.find('CONST_FLOW_CUT_OFF').text.lower() == 'true') else False
	CONST_JUNCTIONS_TO_MEASURE = []#root.find('CONST_JUNCTIONS_TO_MEASURE').text.split(",")
	CONST_EXPERIMENT_NAME = root.find('CONST_EXPERIMENT_NAME').text
	CONST_GUI = True if (root.find('CONST_GUI').text.lower() == 'true') else False
	# print 'CONST_MAXSIZE:' + str(CONST_MAXSIZE)
	# print 'CONST_MINSIZE:' + str(CONST_MINSIZE)
	# print 'CONST_STOP_SPEED:' + str(CONST_STOP_SPEED)
	# print 'CONST_SEARCH_DISTANCE:' + str(CONST_SEARCH_DISTANCE)
	# print 'CONST_MIN_PLATOON_DISTANCE:' + str(CONST_MIN_PLATOON_DISTANCE)
	# print 'CONST_EXIT_PLATOON_BUFFER:' + str(CONST_EXIT_PLATOON_BUFFER)
	# print 'CONST_SPLIT_DISTANCE:' + str(CONST_SPLIT_DISTANCE)
	# print 'CONST_LANE_CHANGE_DURATION:' + str(CONST_LANE_CHANGE_DURATION)
	# print 'CONST_PROPORTION_CONNECTED_VEHICLES:' + str(CONST_PROPORTION_CONNECTED_VEHICLES)
	# print 'CONST_TAU_UNCONNECTED:' + str(CONST_TAU_UNCONNECTED)
	# print 'CONST_TAU_CONNECTED_NO_PLATOON:' + str(CONST_TAU_CONNECTED_NO_PLATOON)
	# print 'CONST_TAU_CONNECTED_PLATOON:' + str(CONST_TAU_CONNECTED_PLATOON)
	# print 'CONST_ENABLE_PLATOONING:' + str(CONST_ENABLE_PLATOONING)
	# print 'CONST_CURR_MAP:' + str(CONST_CURR_MAP)
	# print 'CONST_MEASURE_ALL_JUNCTIONS:' + str(CONST_MEASURE_ALL_JUNCTIONS)
	# print 'CONST_MEASUREMENT_INTERVAL:' + str(CONST_MEASUREMENT_INTERVAL)
	# print 'CONST_FLOW_FILE_NAME:' + str(CONST_FLOW_FILE_NAME)
	# print 'CONST_FLOW_SIMULATION_TIME:' + str(CONST_FLOW_SIMULATION_TIME)
	# print 'CONST_FLOW_CUT_OFF:' + str(CONST_FLOW_CUT_OFF)
	# print 'CONST_JUNCTIONS_TO_MEASURE:' + str(CONST_JUNCTIONS_TO_MEASURE)
	# print 'CONST_EXPERIMENT_NAME:' + str(CONST_EXPERIMENT_NAME)